El experimento \"pythonPromptNewToolsExt\" estÃ¡ activo
[ERROR 2023-3-2 14:58:6.60]: Cannot update workspace settings as no workspace is opened
> conda info --json
> C:\Users\USUARIO\AppData\Local\Programs\Python\Python310\python.exe -c "import sys;print(sys.executable)"
[ERROR 2023-3-2 14:58:6.494]: [Error: Command failed: C:\Users\USUARIO\AppData\Local\Programs\Python\Python310\python.exe -c "import sys;print(sys.executable)"
/bin/sh: 1: C:UsersUSUARIOAppDataLocalProgramsPythonPython310python.exe: not found

	at ChildProcess.exithandler (node:child_process:399:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)] {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'C:\\Users\\USUARIO\\AppData\\Local\\Programs\\Python\\Python310\\python.exe -c "import sys;print(sys.executable)"'
}
> /bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
> /usr/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
Iniciando el servidor de lenguaje Pylance.
[ERROR 2023-3-2 14:58:6.987]: sendStartupTelemetry() failed. [TypeError: Cannot read properties of undefined (reading 'uri')
	at m (/home/lrb96/.vscode-server/extensions/ms-python.python-2023.6.0/out/client/extension.js:2:705811)
	at t.sendStartupTelemetry (/home/lrb96/.vscode-server/extensions/ms-python.python-2023.6.0/out/client/extension.js:2:706798)]
