Visual Studio Code (1.77.0, wsl, desktop)
Jupyter Extension Version: 2023.3.1000892223.
Python Extension Version: 2023.6.0.
Workspace folder /home/lrb96/librerias_python
info 11:41:18.176: ZMQ loaded via fallback mechanism.
El usuario pertenece al grupo de experimentos 'jupyterEnhancedDataViewer'
El usuario pertenece al grupo de experimentos 'jupyterTest'
info 11:41:18.411: LSP Notebooks experiment is enabled
info 11:41:19.116: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0]) for '/home/lrb96/librerias_python/cuadernos/pandas_platzi/1.Archivos_csv.ipynb' (disableUI=true)
warn 11:41:19.494: Failed to get activated env vars for /bin/python3 in 379ms
warn 11:41:19.494: Failed to get activated env vars for /bin/python3 in 310ms
warn 11:41:19.494: Failed to get activated env vars for /bin/python3 in 83ms
warn 11:41:19.494: Failed to get activated env vars for /bin/python3 in 82ms
info 11:41:19.504: Process Execution: > /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
> /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
info 11:41:19.527: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
info 11:41:19.534: Process Execution: > /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 11:41:19.543: Process Execution: > /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"9445bd15-278f-44ba-a4af-83e7e2fdc5bf" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/lrb96/.local/share/jupyter/runtime/kernel-v2-10693ovBvKfr5ObgI.json
> /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"9445bd15-278f-44ba-a4af-83e7e2fdc5bf" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/lrb96/.local/share/jupyter/runtime/kernel-v2-10693ovBvKfr5ObgI.json
info 11:41:19.543: Process Execution: cwd: ~/librerias_python/cuadernos/pandas_platzi
cwd: ~/librerias_python/cuadernos/pandas_platzi
info 11:41:19.811: ipykernel version & path 6.22.0, ~/.local/lib/python3.8/site-packages/ipykernel/__init__.py for /bin/python3
info 11:41:20.208: ZMQ loaded via fallback mechanism.
info 11:41:20.220: Started Kernel Python 3.8.10 (pid: 10771)
warn 11:41:20.383: Failed to get activated env vars for /bin/python3 in 131ms
info 11:41:20.392: Process Execution: > /bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/pythonFiles/printJupyterDataDir.py
> /bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/pythonFiles/printJupyterDataDir.py
info 11:41:38.829: Cancel all remaining cells true || Error || undefined
info 11:46:01.367: Dispose Kernel '/home/lrb96/librerias_python/cuadernos/pandas_platzi/1.Archivos_csv.ipynb' associated with '/home/lrb96/librerias_python/cuadernos/pandas_platzi/1.Archivos_csv.ipynb'
info 11:46:01.371: Dispose Kernel process 10771.
info 11:46:02.700: Shutting down notebooks for 7d7f1470-9a73-4c2b-97c7-93e6392a5902
info 11:46:02.700: Disposing HostJupyterExecution 9945eb39-571c-4cdd-be63-36e6f8d8869c
info 11:46:02.701: Dispose Kernel '/home/lrb96/librerias_python/cuadernos/pandas_platzi/1.Archivos_csv.ipynb' associated with '/home/lrb96/librerias_python/cuadernos/pandas_platzi/1.Archivos_csv.ipynb'
info 11:46:02.701: Disposing HostJupyterExecution 9945eb39-571c-4cdd-be63-36e6f8d8869c
