Visual Studio Code (1.77.0, wsl, desktop)
Jupyter Extension Version: 2023.3.1000892223.
Python Extension Version: 2023.6.0.
Workspace folder /home/lrb96/librerias_python
info 11:39:34.202: ZMQ loaded via fallback mechanism.
El usuario pertenece al grupo de experimentos 'jupyterEnhancedDataViewer'
El usuario pertenece al grupo de experimentos 'jupyterTest'
info 11:39:34.433: LSP Notebooks experiment is enabled
info 11:39:34.829: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]) for '/home/lrb96/librerias_python/cuadernos/pandas_platzi/1.Archivos_csv.ipynb' (disableUI=true)
warn 11:39:35.261: Failed to get activated env vars for /bin/python3 in 432ms
warn 11:39:35.261: Failed to get activated env vars for /bin/python3 in 430ms
warn 11:39:35.261: Failed to get activated env vars for /bin/python3 in 171ms
warn 11:39:35.261: Failed to get activated env vars for /bin/python3 in 171ms
info 11:39:35.271: Process Execution: > /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
> /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
info 11:39:35.291: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
info 11:39:35.297: Process Execution: > /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 11:39:35.305: Process Execution: > /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"f0a945eb-8bcf-4f3c-9599-ecf66a16da2a" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/lrb96/.local/share/jupyter/runtime/kernel-v2-10425pOZKf63MHXZ1.json
> /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"f0a945eb-8bcf-4f3c-9599-ecf66a16da2a" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/lrb96/.local/share/jupyter/runtime/kernel-v2-10425pOZKf63MHXZ1.json
info 11:39:35.305: Process Execution: cwd: ~/librerias_python/cuadernos/pandas_platzi
cwd: ~/librerias_python/cuadernos/pandas_platzi
info 11:39:35.514: ipykernel version & path 6.22.0, ~/.local/lib/python3.8/site-packages/ipykernel/__init__.py for /bin/python3
info 11:39:35.931: ZMQ loaded via fallback mechanism.
info 11:39:35.944: Started Kernel Python 3.8.10 (pid: 10529)
warn 11:39:36.054: Failed to get activated env vars for /bin/python3 in 76ms
info 11:39:36.144: Process Execution: > /bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/pythonFiles/printJupyterDataDir.py
> /bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/pythonFiles/printJupyterDataDir.py
info 11:39:36.922: Cancel all remaining cells true || Error || undefined
info 11:41:04.450: Shutting down notebooks for 2ca9b879-2f45-42c6-adab-a19a95f573f2
info 11:41:04.450: Disposing HostJupyterExecution 3ad8925d-799b-4fb3-ac1e-30c10b4f38e2
info 11:41:04.450: Dispose Kernel '/home/lrb96/librerias_python/cuadernos/pandas_platzi/1.Archivos_csv.ipynb' associated with '/home/lrb96/librerias_python/cuadernos/pandas_platzi/1.Archivos_csv.ipynb'
info 11:41:04.451: Dispose Kernel process 10529.
info 11:41:04.458: Disposing HostJupyterExecution 3ad8925d-799b-4fb3-ac1e-30c10b4f38e2
